[package]
name = "logging"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
statics = { path = "../statics" }

[features]
std = []

can = []
ble = []
defmt = []


info = ["trace"]
trace = ["debug"]
debug = ["warn"]
warn = ["error"]
error = []
