[package]
name = "logging_test"
version = "0.1.0"
edition = "2021"

[dependencies]
logging = { path = "../", features = ["info", "can"] }


[features]

can = []
ble = []
defmt = []


trace = ["info"]
info = ["debug"]
debug = ["warn"]
warn = ["error"]
error = []
